### ISSUE TITLE
Redirect url

### ISSUE THREAD

**Issue by MOOGAA** [spencerwooo/onedrive-cf-index#120]
I wanna change redirectting url,
What I hav to for that bcz afaik if I hav c_id, c_sec & r_t_ all bind In site variable than I think I don't need it,
I wanna know if it's tru or not

I can bind all var in wrangler.toml than deploy it setting var with site variables

**Comment by MOOGAA** [comment]
Also settings var with site variables is less Hessle than useing kv

**Comment by spencerwooo** [comment]
Can you state your problem more clearly?

> I wanna change redirectting url,

As long as you set the `redirect_uri` the same as what you did at the Microsoft Graph API end, you will be ok. Setting the url to be `http://localhost` on both ends is totally viable.

> I can bind all var in wrangler.toml than deploy it setting var with site variables.

Some variables like `client_secret` should not be commited into a git managed repository, which means setting that explicitly inside `wrangler.toml` is a high security issue, even if your repository is private. I wouldn't recommend such behavior. And that's why some variables being used in this project are set using Cloudflare Worker's secrets (environment variables).

**Comment by MOOGAA** [comment]
I mean I'm used lots of google drive index with that method & all were working as simple deployment

Also the ultimate index which hav backend auth protocol work same with setting var via .toml 

Im Actually confused abt redirectting uri like it it shud be if I want to change or don't want to use it
