### ISSUE TITLE
[Bug] Video black screen

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/onedrive-cf-index#73]
Reproduce: [Multimedia / 车库女王 高跟蹦迪 乘风破浪的姐姐主题曲【醋醋】.mp4](https://storage.spencerwoo.com/%F0%9F%A5%9F%20Some%20test%20files/Multimedia/%E8%BD%A6%E5%BA%93%E5%A5%B3%E7%8E%8B%20%E9%AB%98%E8%B7%9F%E8%B9%A6%E8%BF%AA%20%E4%B9%98%E9%A3%8E%E7%A0%B4%E6%B5%AA%E7%9A%84%E5%A7%90%E5%A7%90%E4%B8%BB%E9%A2%98%E6%9B%B2%E3%80%90%E9%86%8B%E9%86%8B%E3%80%91.mp4)

**Comment by nilay14** [comment]
It is due to codec of the video , It is Hevc(High Efficiency Video Coding) and chrome doesn't support hevc. For that you need to re-encode videos in H.264 or other supportable codec to able to play in Chrome

![image](https://user-images.githubusercontent.com/20761574/105496543-9e69d680-5ce3-11eb-9c7e-2a3c4f2228d8.png)

More Details :- https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#hevc_h.265

**Comment by spencerwooo** [comment]
@nilay14 Thank you for the information!
